project_name: visuche

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./main.go
    binary: visuche

archives:
  - format: tar.gz
    name_template: >-
      visuche_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: visuche
    description: "GitHub repository analytics tool for PR metrics, lead times, and CI/CD performance"
    homepage: "https://github.com/hironeko/visuche"
    license: "MIT"
    folder: Formula
    repository:
      owner: hironeko
      name: homebrew-visuche
    commit_author:
      name: hironeko
      email: hironeko@example.com
    install: |
      bin.install "visuche"
    test: |
      system "#{bin}/visuche", "--help"